basePath: /
definitions:
  todo.Todo:
    properties:
      done:
        type: boolean
      id:
        type: integer
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample todo app with Gin
  title: Todo API
  version: "1.0"
paths:
  /todo/list:
    get:
      description: Get the list of all todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/todo.Todo'
            type: array
      summary: Get todos
      tags:
      - todos
swagger: "2.0"
